### ISSUE TITLE
client.boolVariation throws "TypeError: LaunchdarklyReactNativeClient.boolVariationFallback is not a function."

### ISSUE THREAD

**Issue by samih7** [launchdarkly/react-native-client-sdk#83]
**Describe the bug**
On v4.x.x, when calling `await client.boolVariation(flagName, false);` I get the following warning: _"TypeError: LaunchdarklyReactNativeClient.boolVariationFallback is not a function."_ and the flag isn't returned. 

Works with v3.2.2.

**To reproduce**

- Install `launchdarkly-react-native-client-sdk` v4.0.0 or higher
- Call the `client.boolVariation` function inside React Native app

**Expected behavior**
No error is thrown and the flag is returned from `client.boolVariation`.

**Logs**
```
Possible Unhandled Promise Rejection (id: 0):
TypeError: LaunchdarklyReactNativeClient.boolVariationFallback is not a function. (In 'LaunchdarklyReactNativeClient.boolVariationFallback(flagKey, fallback)', 'LaunchdarklyReactNativeClient.boolVariationFallback' is undefined)
boolVariation@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:307598:69
fetchNewValue$@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:308016:71
tryCatch@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:25663:23
invoke@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:25836:32
tryCatch@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:25663:23
invoke@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:25736:30
http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:25766:19
tryCallTwo@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:3623:9
doResolve@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:3787:25
Promise@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:3646:14
callInvokeWithMethodAndArg@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:25765:33
enqueue@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:25770:157
http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:25787:69
fetchNewValue@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:308011:42
http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:308033:20
commitHookEffectListMount@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:20440:38
commitLifeCycles@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:20491:42
commitLayoutEffects@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:22775:29
invokeGuardedCallbackImpl@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:9999:21
invokeGuardedCallback@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:10093:42
commitRootImpl@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:22564:36
commitRootImpl@[native code]
unstable_runWithPriority@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:46622:30
commitRoot@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:22451:24
performSyncWorkOnRoot@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:21975:19
performSyncWorkOnRoot@[native code]
http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:13248:38
unstable_runWithPriority@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:46622:30
flushSyncCallbackQueueImpl@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:13243:28
flushSyncCallbackQueue@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:13232:35
batchedUpdates$1@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:21994:35
batchedUpdates@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:11248:36
_receiveRootNodeIDEvent@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:11340:23
receiveTouches@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:11393:34
__callFunction@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:2980:36
http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:2708:31
__guard@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:2931:15
callFunctionReturnFlushedQueue@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:2707:21
callFunctionReturnFlushedQueue@[native code]
```

**SDK version**
Tried with v4.2.1, v4.1.2, v4.0.4, v4.0.0

**OS/platform**
iOS

**Comment by bwoskow-ld** [comment]
Hi @samih7,

The string `boolVariationFallback` does not exist in the 4.x codebase, but it does in the 3.x codebase. Is it possible that you incorrectly / incompletely upgraded your React Native SDK dependency from `3.2.2` to the `4.x` series? I expect that you have a mismatch between your `launchdarkly-react-native-client-sdk` NPM package and your `LaunchDarkly` pod dependency. In case it is helpful, [here](https://docs.launchdarkly.com/sdk/client-side/react/react-native) is a link to our reference information for this SDK which includes details on getting started with the latest version.

Cheers,
@bwoskow-ld

**Comment by samih7** [comment]
@bwoskow-ld Thanks for your answer. The issue was still present when simply installing `node_modules` and pods. However, I got it working by:

- Deleting `node_modules`
- Deleting `ios/Pods/`
- Reinstall both
- Uninstall and reinstall React Native app

Closing this issue 👍
